# Introduction

**Welcome to the Translational Neuropsychiatry and Neurotoxicology Lab**.

This manual was developed by Eduardo Garza, lab PI. 

It is intended to be a beginners guide into the lab and to provide my vision of how the lab should function. It is also intended to be a reminder of how to conduct yourself in the lab and with your peers, and to provide information on how to proceed if this code of conduct is not being followed by your peers.

ALL lab members will be expected to read this lab manual. It will update with time.

This manual was inspired by other similar works for example the [Grange-Lab manual](https://bookdown.org/JimGrange/Grange-lab-manual/intro.html). This manual is licence under a [CC Attribution 4.0 Licence](https://creativecommons.org/licenses/by/4.0/).

This is our website [PsiLANTRO Lab](https://psilantrolab.github.io/). 
Make sure to send me your picture to add you as a student on the website.

New students should first do the following:

* Get a [Gmail](https://mail.google.com) account.
* Get a [Github](https://github.com) account.
* Download [Slack](https://slack.com/intl/es-mx/).
* Get a free [Asana](https://asana.com) account.
* Get an [Open Science Framework](https://osf.io) account.
* Let me (Eduardo) know when you do this so I can add you to the lab accounts.
* Ask me for a [C13 Cluster](https://github.com/c13inb/c13inb.github.io/wiki/) account, sending me your full name and program.
* Get [Rocket Chat](https://github.com/c13inb/c13inb.github.io/wiki/rocket.chat) setup and explore the channels. This is where most people who use MRI at the INB get help.


Our [Wiki](https://github.com/psilantrolab/Documentation/wiki) can help you with tutorials and documentation for tools we use at the lab.



