# Overview

## Mission

> “We conduct rigurous basic multi-species research focused on finding behavioral, neuroimaging, and other biological biomarkers in substance use disorders and other neuropsychiatric disorders, to use this knowledge to tackle applied and clinical questions, such as researching new treatments like neuromodulation.”

This mission statement guides all work conducted in the lab, from BSc to independent post-doctoral students. A mission statement is important as it allows the lab to focus our efforts on a particular direction. Neuroscience is a large discipline, and without focus our work will have less impact.

Individual projects won’t (necessarily) address all aspects of this mission statement (except the rigorous part!), but the work of the lab as a whole will. Here I unpack some key terms in this mission statement:

* **Rigorous:** All work conducted in the lab should be rigorously-conducted. We take our science very seriously, and we ensure that the work we conduct is of the highest quality. As part of this rigour, we ensure that our studies are addressing important questions.

* **Basic Research:** Science typically falls into one of two categories: Fundamental (or “basic” / “pure”) research, and Applied research. Fundamental research aims to improve scientific theories, generate new ideas, and discover new empirical phenomena, without the promise of an immediate application of this knowledge. It is often referred to as the pursuit of knowledge for its own sake. An important part of our research strategy is to conduct fundamental research into neuropsychiatric disorders. We conduct this fundamental research to develop a better understanding of substance use disorders and other neuropsychiatric disorders.

* **Multi-species:** To create improvements in diagnosis and treatment of substance use and neuropsychiatric disorders, the basic and traslational study working with several species is fundamental and necessary. We work with mice, rats, non-human primates and humans ethically and respectfully.  

* **Neuroimaging:** Our main tool is magnetic resonance imaging (MRI), however, we also work with other techniques such as microscopy, electroencephalography, local-field potentials, among others. You will need to learn the basics of multiple techniques with a main focus on MRI.

* **Substance Use Disorders:** This is the main topic of research within the lab. All work conducted—whether it is fundamental work or applied—should address a question regarding substance use disorders (SUDs). SUDs refer to any type of substance in multiple species.  

* **Neuropsychiatric disorders:** Here we work in the line between neurology and psychiatry, without separating both that much. Substance use disorders are an example of a neuropsychiatric disorder.

* **Applied and Clinical Questions:** The lab aspires to improve diagnosis and treatment of SUDs and neuropsychiatric disorders by using the knowledge derived from basic multi-species research.

* **Neuromodulation:** It refers to the manipultation of central and/or perpheric nervous systems activity by means of electrical or ultrasonic stimulation or chemical agents. It can be invasive, such as deep brain stimulation and non-invasive, such as trascranial magnetic stimulation. 

## Core values

The lab holds itself to several core values:

* **Ambition:** We are an ambitious lab, and I expect all members to show ambition in their work. I will help you to make sure your project is ambitiously relevant to your current stage (i.e., MSc projects will be more ambitious than BSc projects). Note that this also refers to personal ambition, and is independent of your current ability: I want you to be the best “you” that you can be.
* **Commitment:** Good science requires commitment. You should be committed to your project by having clear goals which are SMART: specific, measurable, attainable, relevant, and time-bound.
* **Enthusiasm:** Hard work is difficult without enthusiasm. It is therefore important that you work on a project that is both of value to the lab’s mission and of interest to you.
* **Excellence:** We strive for excellence in all that we do. No half-done stuff.
* **Honesty:** We value honesty in all of our work and communications, even when this is difficult.
* **Independence:** It is important that we take ownership of our individual projects. We are able to work independently, but importantly feel secure to ask questions when help is required.
* **Team Work:** Although we are all working on independent projects, they all map on to our lab’s mission. We are therefore a **team**, and as such help and support each other as much as possible. We meet regularly, and provide open, honest, and respectful feedback on each other’s work.

## Expectations

### Everyone

We expect each other to:

* Push the envelope of scientific discovery & personal excellence.
* Do work we are proud of individually and as a group.
* Do work that others will care about.
* Double-check our work. Being a little obsessive is essential to good science.
* Be supportive of our lab-mates. We are a team.
* Work independently when we can, but ask for help when we need it.
* Communicate honestly, especially when it is difficult (e.g., share our mistakes).
* Share our knowledge. Mentorship takes many forms.
* Respect each other’s strengths, weaknesses, and differences. Diversity is to be celebrated.
* Respect all types of people and beliefs.
* Be able to work directly or indirectly with multiple species, mainly: mice, rats, non-human primates and humans.

### Principal Investigator

As well as the above, you can expect me to:

* Have a vision for where the lab is going.
* Obtain the funding to support the science, and the people (where appropriate), in the lab.
* Meet with you regularly to discuss your research projects. The definition of “regularly” may change over time or over the course of a project, but unless we agree otherwise the expectation is that this will be once per week.
* Support you in your career development, regardless of your current stage. This includes discussing professional development, writing letters of recommendation, and promoting your work in conference presentations I attend.
* Care about you as a person and not just as a scientist.
* Obsess over many things related to your project & its eventual dissemination, from font choice, punctuation / grammar, and data visualisation. It will drive you nuts.
* Hold high expectations of you: These expectations are there because I believe you can reach them.

### Bachelor Students
* Develop a project that fits with the mission of the lab. If you are unsure on what project you should work on, I can provide a project for you. This will not affect your final grade.
* Communicate frequently with me. One of the skills we wish to develop in you is project management, so keep me up to date regularly with your progress.
* Be punctual with our meetings.
* Care about data quality. Conduct your empirical work under strict lab conditions: minimize distractions; ensure the participant is engaged with the experiment (humans); be consistent with your protocols.
* When conducting experiments, be professional at all times with your participants. Be on time. Be polite. Provide a good debrief. If your subject is a non-human animal, be kind and ethical.
* When you are stuck on a problem, try to solve it yourself first. If you then need help, please ask me. But when you ask, I expect that you tell me what you have tried yourself to solve the problem.
* Keep notes of our meetings. It is up to you to maintain thorough notes to ensure an accurate record of what we discussed and what was agreed.
* Stay up-to-date (and keep me informed) on any deadlines that you need to meet.

### Master Students
As well as the above, I expect Master students to:

* Be more independent in all aspects of the project.
* Develop a line of research that could lead to a publishable piece of work. Although this is not a requirement for the Master degree itself, remember that the lab has high expectations.
* Pre-register your study at the Open Science Framework or similar framework.
* Develop & communicate clear instructions to help me program your experimental with you. Take an active interest in how the experiment is done.
* Learn to program:
    * Learn the statistical programming language R using R Studio.
    * Learn how to use RMarkdown, and eventually writing your reports this way.
    * Understand that there is a steep learning curve associated with all of the above, but that you will be better off for having learned them.
* Take the lead on data preparation and analysis.
* Share your data & analysis publicly. I'll tell you how as this changes everyday.
* Develop a healthy work–life balance.
    * Take time off regularly, guilt-free. I will do the same.
    * Practice self-care
    * Realize there are times for pulling all-nighters, and times for not coming into work and having some fun.

### PhD Students
As well as the above, I expect PhD students to:

* Strive to know the literature related to your topic like the back of your hand.
* Develop a line of dissertation research leading to publishable output (conferences and journal papers).
* Seek out and apply for fellowship and awards (including travel awards for conference attendance etc.).
* Develop as an independent scientist:
    * In Year 1, be guided by my instructions
    * In Year 2, challenge some of my instructions & start to tell me what you’re doing
    *In Year 3+, take full ownership
* Consider contributing to teaching where possible, but especially if you wish to pursue an academic career post-PhD. Some options could be:
    * Lead seminars
    * Teach in my courses
    * Co-supervise Bachelor and Master student projects.