# Communication

I am usually busier than I would like to be, and as a result have less time for talking to people than I would like. However, you (lab members) are one of the most important parts of my job, and I need your help to stay organised and involved in the things that I need to be involved in. Some general guidelines:

1. **Be proactive.** Tell me what you need. This includes coming to knock on my door, emailing me, setting up a meeting, or catching me in the corridor.

2. **Write things down** and remind me what we’ve talked about. I would love to remember every small detail that we decided when we met last week, but this doesn’t always happen. Don’t hesitate to bring me up to speed when we meet. Even if I already remember what we are talking about, a couple of introductory topic sentences will help us both get in the right frame of mind. Be sure to take notes of our meetings.

3. **Read all of the lab documentation.** That includes this lab manual, but also your course documentation. You are responsible for knowing what is in each of these places, following the rules and guidelines we have set up, and notifying someone if you find incorrect information (or if you have questions).

4. **Be strategic in what you ask me.** Please check the lab manual, University / School documentation, and/or a Google search before asking me something.

## My door

Metaphorically, my door is always open, but sometimes my door is physically closed. If this is the case:

* If we have a meeting scheduled for that time, please do knock even if I am in a meeting. Sometimes I will continue a meeting if it seems that my next appointment has not turned up, so please do let me know you have arrived.
    * If I don't answer the door it means I cannot open. Send me a message instead.
* If we do not have a meeting scheduled, consider instead dropping me an email. Of course, if it’s an emergency then please knock anyway.

## Email

Now that the lab has moved to Slack for team communication, I tend to rely less on my email as the primary form of communication with lab members. I would therefore strongly encourage you to communicate with me via Slack rather than email. However, you can of course send an email if you would prefer, especially for more sensitive matters. 
    
## Booking a meeting with me
Email me if you need a meeting. I'll check my schedule and book you.

## Lab meetings
We meet collectively once each week to talk about science together, to discuss common issues, and to make sure we have a chance to discuss our individual research projects. Regular attendance is expected, as is active-participation (presenting, asking questions, etc).